### ISSUE TITLE
War machine outdated... :(

### ISSUE THREAD

**Issue by djfg0** [ska42/libft-war-machine#14]
- The moulinette expects bonus functions to be suffixed with _bonus, but War machine doesn't know about it. So, it doesn't test the functions.

- Even if I change my function names + Makefile, the tests abort because of fsanitize raising an error in your mains.

![Screen Shot 2019-12-05 at 9 47 11 PM](https://user-images.githubusercontent.com/44943107/70272859-443d4780-17a9-11ea-9105-fad8d39d6340.png)

![Screen Shot 2019-12-05 at 9 52 48 PM](https://user-images.githubusercontent.com/44943107/70273040-9a11ef80-17a9-11ea-85df-5ea1c1b7de96.png)

**Comment by ska42** [comment]
should work on https://github.com/ska42/libft-war-machine/commit/e082bacb4bd7a62fd8918999df4cce043f9a899e
👍
