### ISSUE TITLE
Problem with memchr.c

### ISSUE THREAD

**Issue by irlalmeida** [ska42/libft-war-machine#18]
```
= ft_memchr.c ==================================================================
$> norminette ft_memchr.c | grep -E '(Error|Warning)'

norminette : command not found

$> clang -Wextra -Wall -Werror -g3 -fsanitize=address ft_memchr.c main.c libft.a -o user_exe

/home/irlalmeida/Documents/VSCode/42/libft-war-machine/tests/Part1_functions/ft_memchr/main.c:81:16: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
                printf("%s", ft_memchr(tab, -1, 7));
                        ~~   ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I believe the error is with the program itself because the code compiles with other testers. However, I haven't submitted it to Moullinete yet

**Comment by ska42** [comment]
For this one i'm assuming you're using linux, because on mac the problem doesn't show up, I will just fix it by casting to (char *) mem_chr, thx !

**Comment by ska42** [comment]
Should be fix on: https://github.com/ska42/libft-war-machine/commit/7a82f44f796f7aa77f6aa3033aba471d86883521
Ask me anything if you have any other problem !
