### ISSUE TITLE
[BUG] War Machine incorrectly expects bonus part files to be named with the _bonus suffix

### ISSUE THREAD

**Issue by paulo-santana** [ska42/libft-war-machine#19]
I saw that the issue #14 stated that the bonus files (about linked lists) are expected to be ended with _bonus.c. But this is false. The _bonus suffix is meant to name files that contains functions which weren't asked in the subject.

I don't believe Moulinette will mark a file name as wrong, since they don't specify any. But this behavior makes this tester the only which doesn't grade the linked list bonus functions.

**Comment by ska42** [comment]
Should work for both (with or without _bonus) in 4bd5b642f990334b5f5266b5d761500f4a8ca719 :)
