### ISSUE TITLE
[BUG] warmashine incorrectly finds "forbidden" functions in the bonus part

### ISSUE THREAD

**Issue by fabinca** [ska42/libft-war-machine#20]

**Comment by ska42** [comment]
test-case ? description ? screen ?

**Comment by fabinca** [comment]
Sure sorry. So Actually I just re-did the tests and now I'm not so sure about this. What I did is this: 
1. test my libft with warmashine - bonus functions are clean 
2. test my code with libft-unit-test (make f) https://github.com/alelievr/libft-unit-test 
3. test my code with warmashine: bonus functions are not clean
![image](https://user-images.githubusercontent.com/73344238/120318278-f80c8e00-c2df-11eb-854a-418588a99fa7.png)
4. test my code with warmashine again: bonus functions are clean again.. 

And after rechecking again it seems this error appears not because of forbidden functions but because there are .o files and libft.so and libft.a and a.out in the directory.

**Comment by ska42** [comment]
Should be fixed on 2219b4a9b8dfb2a40fa990d909efdee2a7f36794 :)
