### ISSUE TITLE
Do not work !

### ISSUE THREAD

**Issue by RoyaLProg** [ska42/libft-war-machine#28]
After few tries impossible to make the script work

Whateveer i do, the "path" was not the correct one it always take the path of the tester ...

`clang: error: no such file or directory: '/mnt/c/.../42project/libft-war-machine/dirlibft/libft.a'`

Seems like it happen only on compilation time ...

I'm using a WSL2 (kali-linux)

**Comment by ska42** [comment]
did you update the path of your libft in `my_config.sh`?

**Comment by RoyaLProg** [comment]
It does not, and yeah; i updated it 3 times with and without double quote, relative or absolute path

**Comment by ska42** [comment]
Can you show me what have you tried ?
and do you know which line or the tester give you this err output ?

**Comment by RoyaLProg** [comment]
```
PATH_LIBFT=/mnt/c/[...]/42Project/libft
PATH_LIBFT="/mnt/c/[...]/42Project/libft"
PATH_LIBFT=../libft
PATH_LIBFT="../libft"
```

compilation is the one who fail i guess :

`ft_memset             ok             failure     compil. failed   compil. failed      KO`

(all the output line look like this)

**Comment by ska42** [comment]
Your path seems fine yup..
Yep but that don't explain why it failed :p
Have you subdir in your libft ? Have you a Makefile ?

**Comment by RoyaLProg** [comment]
No subdir, have a makefile

ps : je t'envoie un message tout de suite

**Comment by RoyaLProg** [comment]
Solution :

add re and debugging makefile
